apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: legacy-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
      - name: main
        image: gcr.io/gke-on-prem-next-demo-2/loadgenerator
        env:
        - name: FRONTEND_ADDR
          value: "productpage.bookinfo:9080"
