apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookinfo-client
  namespace: bookinfo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
      - name: main
        image: gcr.io/gke-on-prem-next-demo-2/loadgenerator:23ac1ce
        imagePullPolicy: IfNotPresent
        env:
        - name: FRONTEND_ADDR
          value: "productpage:9080"
